=== scitran/core/swagger/schemas/mongo/session.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Session",
    "type": "object",
    "allOf": [{"$ref": "container.json"}],
    "properties": {
        "_id": {},
        "created": {},
        "modified": {},
        "permissions": {},
        "files": {},
        "public": {},
        "label": {},
        "satisfies_template": {"type": "boolean"},
        "project_has_template": {"type": "boolean"},
        "tags": {},
        "info": {},
        "operator": {},
        "group":        {"type": "string"},
        "project":      {},
        "uid":          {"type": "string"},
        "timestamp":    {},
        "timezone":     {"type": "string"},
        "subject":      {"$ref": "subject.json"}
    },
    "additionalProperties": false
}

=== scitran/core/raml/examples/output/session.json
{
	"group": "scitran",
	"created": "2016-09-19T17:13:48.164000+00:00",
	"subject": {
		"code": "ex4784",
		"_id": "57e01cccb1dc04000fb83f02"
	},
	"modified": "2016-09-19T17:13:48.164000+00:00",
	"label": "control_1",
	"project": "57e01cccf6b5d5edbcb4e1cf",
	"_id": "57e01cccb1dc04000fb83f03",
	"public": false,
	"permissions": [{
		"access": "admin",
		"_id": "coltonlw@flywheel.io",
      	"phi-access": true
	}]
}
